MONGODB_HOST=127.0.0.1

MONGODB_PORT=27018

MONGODB_DATABASE=ecommerce_mongodb

MONGODB_VERSION=8.0.12

MONGOSH_VERSION=2.5.8

RBAC_ENABLED=true
MONGODB_AUTHORIZATION_ENABLED=true
RBAC_ADMIN_USERNAME=admin
RBAC_ADMIN_PASSWORD=Adminrbac
RBAC_DEVELOPER_USERNAME=developer
RBAC_DEVELOPER_PASSWORD=Developerrbac123
RBAC_QA_USERNAME=qa
RBAC_QA_PASSWORD=Qarbac123
RBAC_VIEWER_USERNAME=viewer
RBAC_VIEWER_PASSWORD=Viewerrbac123

MONGODB_VERSION=8.0.12

MONGOSH_VERSION=2.5.8