MONGODB_HOST=127.0.0.1

MONGODB_PORT=27018

MONGODB_DATABASE=EcommerceMongoDB
RBAC_ENABLED=true
MONGODB_AUTHORIZATION_ENABLED=true
RBAC_ADMIN_USERNAME=admin
RBAC_ADMIN_PASSWORD=ChangeMe_Admin_2026!
RBAC_DEVELOPER_USERNAME=developer
RBAC_DEVELOPER_PASSWORD=ChangeMe_Developer_2026!
RBAC_QA_USERNAME=qa
RBAC_QA_PASSWORD=ChangeMe_QA_2026!
RBAC_VIEWER_USERNAME=viewer
RBAC_VIEWER_PASSWORD=ChangeMe_Viewer_2026!

MONGODB_VERSION=8.0.12

MONGOSH_VERSION=2.5.8
