POSTGRESQL_HOST=127.0.0.1
POSTGRESQL_PORT=5434
POSTGRESQL_DB=DataManagementDB
POSTGRESQL_USER=postgres
POSTGRESQL_PASSWORD=root1234
RBAC_ENABLED=true
RBAC_ADMIN_USERNAME=admin
RBAC_ADMIN_PASSWORD=ChangeMe_Admin_2026!
RBAC_DEVELOPER_USERNAME=developer
RBAC_DEVELOPER_PASSWORD=ChangeMe_Developer_2026!
RBAC_QA_USERNAME=qa
RBAC_QA_PASSWORD=ChangeMe_QA_2026!
RBAC_VIEWER_USERNAME=viewer
RBAC_VIEWER_PASSWORD=ChangeMe_Viewer_2026!

POSTGRESQL_VERSION=17
POSTGRESQL_DRIVER_VERSION=42.7.3
LIQUIBASE_VERSION=5.0.3
