changeLogFile=master.xml

url=jdbc:postgresql://localhost:5432/DataManagementDB

username=postgres

password=

driver=org.postgresql.Driver

classpath=../../tools/drivers/postgresql-42.7.3.jar

liquibase.hub.mode=off

logLevel=info

defaultSchemaName=public
