# ============================================================
# SQL Server Enterprise Configuration
# ============================================================

[sqlserver]

INSTANCE_NAME=MSSQLSERVER
DATABASE_NAME=DataManagementDB
PORT=1433

SA_USERNAME=SA
SA_PASSWORD=TerraformSA@2022!

INSTALLER_NAME=SQLServer2022-DEV-x64-ENU.exe

DOWNLOAD_URL=https://download.microsoft.com/download/3/8/d/38de7036-2433-4207-8eae-06e247e17b25/SQLServer2022-DEV-x64-ENU.exe

[paths]

DOWNLOAD_DIR=databases/sqlserver/downloads

TERRAFORM_DIR=terraform/sqlserver

LOG_DIR=logs

SQL_DIR=sql

[terraform]

AUTO_APPROVE=true

[validation]

ENABLE_SQLCMD_VALIDATION=true
ENABLE_DATABASE_VALIDATION=true
ENABLE_TABLE_VALIDATION=true
ENABLE_SEED_VALIDATION=true
ENABLE_SERVICE_VALIDATION=true



LIQUIBASE_VERSION=5.0.3