
pipeline {

    agent any

    parameters {

        choice(
            name: 'DATABASE',
            choices: ['MYSQL', 'MONGODB', 'POSTGRESQL'],
            description: 'Select Database'
        )

        choice(
            name: 'ACTION',
            choices: ['SETUP', 'LOAD'],
            description: 'Select Action'
        )
    }

    stages {

        /*
        ============================================================
        MYSQL SETUP
        ============================================================
        */

        stage('MySQL Setup') {

            when {
                allOf {
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/common/validate_java_runtime.sh

                    ./scripts/bash/mysql/setup/install_tools.sh

                    ./scripts/bash/mysql/setup/install_mysql.sh

                    ./scripts/bash/mysql/setup/deploy_mysql.sh

                    ./scripts/bash/mysql/setup/start_mysql.sh

                    ./scripts/bash/mysql/setup/create_database.sh

                    ./scripts/bash/mysql/setup/validate_environment.sh
                '''
            }
        }


        /*
        ============================================================
        MYSQL LOAD
        ============================================================
        */

        stage('MySQL Load') {

            when {
                allOf {
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/mysql/setup/install_python_requirements.sh

                    ./scripts/bash/mysql/setup/validate_python_requirements.sh

                    ./scripts/bash/mysql/setup/start_mysql.sh

                    ./scripts/bash/mysql/setup/validate_mysql.sh

                    ./scripts/bash/mysql/load/load_data.sh

                    ./scripts/bash/mysql/load/validate_loaded_data.sh
                '''
            }
        }


        /*
        ============================================================
        MONGODB SETUP
        ============================================================
        */

        stage('MongoDB Setup') {

            when {
                allOf {
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    chmod -R +x scripts/bash

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/common/install_python_requirements.sh

                    ./scripts/bash/mongodb/setup/install_mongodb.sh

                    ./scripts/bash/mongodb/setup/install_mongosh.sh

                    ./scripts/bash/mongodb/setup/configure_global_mongosh.sh

                    ./scripts/bash/mongodb/setup/start_mongodb.sh

                    ./scripts/bash/mongodb/setup/configure_mongodb_service.sh

                    ./scripts/bash/mongodb/setup/validate_mongodb.sh
                '''
            }
        }


        /*
        ============================================================
        MONGODB LOAD
        ============================================================
        */

        stage('MongoDB Load') {

            when {
                allOf {
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    chmod -R +x scripts/bash

                    ./scripts/bash/common/install_python_requirements.sh

                    ./scripts/bash/mongodb/setup/start_mongodb.sh

                    ./scripts/bash/mongodb/setup/validate_mongodb.sh

                    ./scripts/bash/mongodb/load/load_data.sh

                    ./scripts/bash/mongodb/load/validate_loaded_data.sh
                '''
            }
        }


        /*
        ============================================================
        POSTGRESQL SETUP
        ============================================================
        */

        stage('PostgreSQL Setup') {

            when {
                allOf {
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/postgresql/setup/install_python_requirements.sh

                    ./scripts/bash/postgresql/setup/validate_python_requirements.sh

                    ./scripts/bash/common/validate_java_runtime.sh

                    ./scripts/bash/postgresql/setup/install_tools.sh

                    ./scripts/bash/postgresql/setup/deploy_postgresql.sh

                    ./scripts/bash/postgresql/setup/install_postgresql.sh

                    ./scripts/bash/postgresql/setup/start_postgresql.sh

                    ./scripts/bash/postgresql/setup/configure_postgresql.sh

                    ./scripts/bash/postgresql/setup/create_database.sh

                    ./scripts/bash/postgresql/setup/configure_global_psql.sh

                    ./scripts/bash/postgresql/setup/validate_postgresql.sh

                    ./scripts/bash/postgresql/setup/validate_environment.sh
                '''
            }
        }


        /*
        ============================================================
        POSTGRESQL LOAD
        ============================================================
        */

        stage('PostgreSQL Load') {

            when {
                allOf {
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/postgresql/setup/install_python_requirements.sh

                    ./scripts/bash/postgresql/setup/validate_python_requirements.sh

                    ./scripts/bash/postgresql/setup/start_postgresql.sh

                    ./scripts/bash/postgresql/setup/validate_postgresql.sh

                    ./scripts/bash/postgresql/load/load_data.sh

                    ./scripts/bash/postgresql/load/validate_loaded_data.sh
                '''
            }
        }
    }

    post {

        success {
            echo "${params.DATABASE} ${params.ACTION} SUCCESSFUL"
        }

        failure {
            echo "${params.DATABASE} ${params.ACTION} FAILED"
        }

        always {
            echo "PIPELINE COMPLETED"
        }
    }
}

