
pipeline {

    agent any

    options {
        disableConcurrentBuilds()
    }

    parameters {

        choice(
            name: 'OPERATING_SYSTEM',
            choices: ['UBUNTU', 'WINDOWS'],
            description: 'Select Operating System'
        )

        choice(
            name: 'DATABASE',
            choices: ['MYSQL', 'MONGODB', 'POSTGRESQL'],
            description: 'Select Database'
        )

        choice(
            name: 'ACTION',
            choices: ['SETUP', 'LOAD'],
            description: 'Select Action'
        )
    }

    stages {

        /*
        ============================================================
        UBUNTU - MYSQL SETUP
        ============================================================
        */

        stage('Ubuntu MySQL Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/common/validate_java_runtime.sh

                    ./scripts/bash/mysql/setup/install_tools.sh

                    ./scripts/bash/mysql/setup/install_mysql.sh

                    ./scripts/bash/mysql/setup/deploy_mysql.sh

                    ./scripts/bash/mysql/setup/start_mysql.sh

                    ./scripts/bash/mysql/setup/create_database.sh

                    ./scripts/bash/mysql/setup/validate_environment.sh
                '''
            }
        }


        /*
        ============================================================
        UBUNTU - MYSQL LOAD
        ============================================================
        */

        stage('Ubuntu MySQL Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/mysql/setup/install_python_requirements.sh

                    ./scripts/bash/mysql/setup/validate_python_requirements.sh

                    ./scripts/bash/mysql/setup/start_mysql.sh

                    ./scripts/bash/mysql/setup/validate_mysql.sh

                    ./scripts/bash/mysql/load/load_data.sh

                    ./scripts/bash/mysql/load/validate_loaded_data.sh
                '''
            }
        }


        /*
        ============================================================
        UBUNTU - MONGODB SETUP
        ============================================================
        */

        stage('Ubuntu MongoDB Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    chmod -R +x scripts/bash

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/common/install_python_requirements.sh

                    ./scripts/bash/mongodb/setup/install_mongodb.sh

                    ./scripts/bash/mongodb/setup/install_mongosh.sh

                    ./scripts/bash/mongodb/setup/configure_global_mongosh.sh

                    ./scripts/bash/mongodb/setup/start_mongodb.sh

                    ./scripts/bash/mongodb/setup/configure_mongodb_service.sh

                    ./scripts/bash/mongodb/setup/validate_mongodb.sh
                '''
            }
        }


        /*
        ============================================================
        UBUNTU - MONGODB LOAD
        ============================================================
        */

        stage('Ubuntu MongoDB Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    chmod -R +x scripts/bash

                    ./scripts/bash/common/install_python_requirements.sh

                    ./scripts/bash/mongodb/setup/start_mongodb.sh

                    ./scripts/bash/mongodb/setup/validate_mongodb.sh

                    ./scripts/bash/mongodb/load/load_data.sh

                    ./scripts/bash/mongodb/load/validate_loaded_data.sh
                '''
            }
        }


        /*
        ============================================================
        UBUNTU - POSTGRESQL SETUP
        ============================================================
        */

        stage('Ubuntu PostgreSQL Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/postgresql/setup/install_python_requirements.sh

                    ./scripts/bash/postgresql/setup/validate_python_requirements.sh

                    ./scripts/bash/common/validate_java_runtime.sh

                    ./scripts/bash/postgresql/setup/install_tools.sh

                    ./scripts/bash/postgresql/setup/deploy_postgresql.sh

                    ./scripts/bash/postgresql/setup/install_postgresql.sh

                    ./scripts/bash/postgresql/setup/start_postgresql.sh

                    ./scripts/bash/postgresql/setup/configure_postgresql.sh

                    ./scripts/bash/postgresql/setup/create_database.sh

                    ./scripts/bash/postgresql/setup/configure_global_psql.sh

                    ./scripts/bash/postgresql/setup/validate_postgresql.sh

                    ./scripts/bash/postgresql/setup/validate_environment.sh
                '''
            }
        }


        /*
        ============================================================
        UBUNTU - POSTGRESQL LOAD
        ============================================================
        */

        stage('Ubuntu PostgreSQL Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'UBUNTU' }
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                sh '''
                    find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                    ./scripts/bash/common/validate_python_runtime.sh

                    ./scripts/bash/postgresql/setup/install_python_requirements.sh

                    ./scripts/bash/postgresql/setup/validate_python_requirements.sh

                    ./scripts/bash/postgresql/setup/start_postgresql.sh

                    ./scripts/bash/postgresql/setup/validate_postgresql.sh

                    ./scripts/bash/postgresql/load/load_data.sh

                    ./scripts/bash/postgresql/load/validate_loaded_data.sh
                '''
            }
        }


        /*
        ============================================================
        WINDOWS - MYSQL SETUP
        ============================================================
        */

        stage('Windows MySQL Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\mysql\\setup\\install_python_requirements.bat'

                bat 'scripts\\batch\\mysql\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\common\\validate_java_runtime.bat'

                bat 'scripts\\batch\\mysql\\setup\\install_tools.bat'

                bat 'scripts\\batch\\mysql\\setup\\deploy_mysql.bat'

                bat 'scripts\\batch\\mysql\\setup\\start_mysql.bat'

                bat 'scripts\\batch\\mysql\\setup\\create_database.bat'

                bat 'scripts\\batch\\mysql\\setup\\validate_environment.bat'
            }
        }


        /*
        ============================================================
        WINDOWS - MYSQL LOAD
        ============================================================
        */

        stage('Windows MySQL Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\mysql\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\mysql\\setup\\start_mysql.bat'

                bat 'scripts\\batch\\mysql\\setup\\validate_mysql.bat'

                bat 'scripts\\batch\\mysql\\load\\load_data.bat'

                bat 'scripts\\batch\\mysql\\load\\validate_loaded_data.bat'
            }
        }


        /*
        ============================================================
        WINDOWS - MONGODB SETUP
        ============================================================
        */

        stage('Windows MongoDB Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\mongodb\\setup\\install_python_requirements.bat'

                bat 'scripts\\batch\\mongodb\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\common\\validate_java_runtime.bat'

                bat 'scripts\\batch\\mongodb\\setup\\install_tools.bat'

                bat 'scripts\\batch\\mongodb\\setup\\validate_tools.bat'

                bat 'scripts\\batch\\mongodb\\setup\\run_terraform.bat'

                bat 'scripts\\batch\\mongodb\\setup\\start_mongodb.bat'

                bat 'scripts\\batch\\mongodb\\setup\\validate_mongodb.bat'
            }
        }


        /*
        ============================================================
        WINDOWS - MONGODB LOAD
        ============================================================
        */

        stage('Windows MongoDB Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'MONGODB' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\mongodb\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\mongodb\\setup\\start_mongodb.bat'

                bat 'scripts\\batch\\mongodb\\setup\\validate_mongodb.bat'

                bat 'scripts\\batch\\mongodb\\load\\load_data.bat'

                bat 'scripts\\batch\\mongodb\\load\\validate_loaded_data.bat'
            }
        }


        /*
        ============================================================
        WINDOWS - POSTGRESQL SETUP
        ============================================================
        */

        stage('Windows PostgreSQL Setup') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\postgresql\\setup\\install_python_requirements.bat'

                bat 'scripts\\batch\\postgresql\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\common\\validate_java_runtime.bat'

                bat 'scripts\\batch\\postgresql\\setup\\install_tools.bat'

                bat 'scripts\\batch\\postgresql\\setup\\deploy_postgresql.bat'

                bat 'scripts\\batch\\postgresql\\setup\\start_postgresql.bat'

                bat 'scripts\\batch\\postgresql\\setup\\create_database.bat'

                bat 'scripts\\batch\\postgresql\\setup\\validate_environment.bat'
            }
        }


        /*
        ============================================================
        WINDOWS - POSTGRESQL LOAD
        ============================================================
        */

        stage('Windows PostgreSQL Load') {

            when {
                allOf {
                    expression { params.OPERATING_SYSTEM == 'WINDOWS' }
                    expression { params.DATABASE == 'POSTGRESQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }

            steps {

                bat 'scripts\\batch\\common\\validate_python_runtime.bat'

                bat 'scripts\\batch\\postgresql\\setup\\validate_python_requirements.bat'

                bat 'scripts\\batch\\postgresql\\setup\\start_postgresql.bat'

                bat 'scripts\\batch\\postgresql\\setup\\validate_postgresql.bat'

                bat 'scripts\\batch\\postgresql\\load\\load_data.bat'

                bat 'scripts\\batch\\postgresql\\load\\validate_loaded_data.bat'
            }
        }
    }


    post {

        success {
            echo "${params.OPERATING_SYSTEM} ${params.DATABASE} ${params.ACTION} SUCCESSFUL"
        }

        failure {
            echo "${params.OPERATING_SYSTEM} ${params.DATABASE} ${params.ACTION} FAILED"
        }

        always {
            echo "MASTER DATABASE PIPELINE COMPLETED"
        }
    }
}
