pipeline {
    agent any

    parameters {
        choice(
            name: 'DATABASE',
            choices: ['MYSQL', 'MONGODB', 'POSTGRESQL'],
            description: 'Select Database'
        )

        choice(
            name: 'ACTION',
            choices: ['SETUP', 'LOAD'],
            description: 'Select Action'
        )
    }

    stages {

        stage('MySQL Setup') {
            when {
                allOf {
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'SETUP' }
                }
            }
            steps {
                sh '''
                chmod +x scripts/bash/common/*.sh
                chmod +x scripts/bash/mysql/*.sh

                ./scripts/bash/common/validate_python_runtime.sh
                ./scripts/bash/common/validate_java_runtime.sh
                ./scripts/bash/common/install_tools.sh
                ./scripts/bash/mysql/install_mysql.sh
                ./scripts/bash/mysql/start_mysql.sh
                ./scripts/bash/mysql/create_database.sh
                ./scripts/bash/mysql/run_liquibase.sh
                ./scripts/bash/mysql/validate_environment.sh
                '''
            }
        }

        stage('MySQL Load') {
            when {
                allOf {
                    expression { params.DATABASE == 'MYSQL' }
                    expression { params.ACTION == 'LOAD' }
                }
            }
            steps {
                sh '''
                find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;

                ./scripts/bash/common/validate_python_runtime.sh
                ./scripts/bash/install_python_requirements.sh
                ./scripts/bash/validate_python_requirements.sh
                ./scripts/bash/common/install_tools.sh
                ./scripts/bash/common/validate_tools.sh
                ./scripts/bash/mysql/validate_mysql.sh
                ./scripts/bash/mysql/load_data.sh
                ./scripts/bash/mysql/validate_loaded_data.sh
                '''
            }
        }

/*
============================================================
MONGODB SETUP
============================================================
*/

stage('MongoDB Setup') {

    when {
        allOf {
            expression { params.DATABASE == 'MONGODB' }
            expression { params.ACTION == 'SETUP' }
        }
    }

    steps {

        sh '''
            chmod +x scripts/bash/common/*.sh
            chmod +x scripts/bash/mongodb/*.sh

            ./scripts/bash/common/validate_python_runtime.sh

            ./scripts/bash/common/install_python_requirements.sh

            ./scripts/bash/mongodb/install_mongodb.sh

            ./scripts/bash/mongodb/install_mongosh.sh

            ./scripts/bash/mongodb/start_mongodb.sh

            ./scripts/bash/mongodb/validate_mongodb.sh
        '''

    }
}

/*
============================================================
MONGODB LOAD
============================================================
*/

stage('MongoDB Load') {

    when {
        allOf {
            expression { params.DATABASE == 'MONGODB' }
            expression { params.ACTION == 'LOAD' }
        }
    }

    steps {

        sh '''
            chmod +x scripts/bash/common/*.sh
            chmod +x scripts/bash/mongodb/*.sh

            ./scripts/bash/common/install_python_requirements.sh

            ./scripts/bash/mongodb/start_mongodb.sh

            ./scripts/bash/mongodb/validate_mongodb.sh

            ./scripts/bash/mongodb/load_data.sh

            ./scripts/bash/mongodb/validate_loaded_data.sh
        '''

    }
}
/*
============================================================
POSTGRESQL SETUP
============================================================
*/

stage('PostgreSQL Setup') {

    when {
        allOf {
            expression { params.DATABASE == 'POSTGRESQL' }
            expression { params.ACTION == 'SETUP' }
        }
    }

    steps {

        checkout scm

        sh 'ls -la'

        sh '''
            find scripts/bash -type f -name "*.sh" -exec chmod +x {} \\;
        '''

        sh 'bash scripts/bash/common/validate_python_runtime.sh'

        sh 'bash scripts/bash/install_python_requirements.sh'

        sh 'bash scripts/bash/validate_python_requirements.sh'

        sh 'bash scripts/bash/common/validate_java_runtime.sh'

        sh 'bash scripts/bash/common/install_tools.sh'

        sh 'bash scripts/bash/postgresql/deploy_postgresql.sh'

        sh 'bash scripts/bash/postgresql/validate_postgresql.sh'
    }
}

/*
============================================================
POSTGRESQL LOAD
============================================================
*/

stage('PostgreSQL Load') {

    when {
        allOf {
            expression { params.DATABASE == 'POSTGRESQL' }
            expression { params.ACTION == 'LOAD' }
        }
    }

    steps {

        sh 'ls -la'

        sh 'chmod -R +x scripts/bash/'

        sh 'scripts/bash/common/validate_python_runtime.sh'

        sh 'scripts/bash/postgresql/validate_environment.sh'

        sh 'python3 scripts/python/postgresql/generate_dataset.py'

        sh 'python3 scripts/python/postgresql/testcsvschema.py'

        sh 'scripts/bash/postgresql/load_data.sh'

        sh 'scripts/bash/postgresql/validate_loaded_data.sh'

        sh 'scripts/bash/postgresql/validate_postgresql.sh'
    }
}
        // ...same pattern...
    }

    post {
        success {
            echo "${params.DATABASE} ${params.ACTION} SUCCESSFUL"
        }

        failure {
            echo "${params.DATABASE} ${params.ACTION} FAILED"
        }

        always {
            echo "Pipeline Completed"
        }
    }
}