#############################################
# Dataset Configuration
#############################################

# Supported values:
# google_drive
# local
SOURCE_TYPE=google_drive

#############################################
# Dataset Source
#############################################

# Examples
#
# Google Drive
# https://drive.google.com/file/d/xxxxx/view
#
# Local
# D:\Datasets\dataset.zip
#
# S3
# bucket/folder/dataset.zip
#
# Azure Blob
# container/folder/dataset.zip
#
SOURCE_PATH=

#############################################
# Dataset
#############################################

DATASET_NAME=testdatasmall.zip

DOWNLOAD_DIRECTORY=incoming/archive

AUTO_EXTRACT=true

DELETE_ARCHIVE=false

FORCE_DOWNLOAD=false

FORCE_EXTRACT=false