MSSQL_HOST=localhost
MSSQL_PORT=1533

MSSQL_DB=EcommerceMSSQL

MSSQL_USER=sa
MSSQL_PASSWORD=TerraformSA@2022!

MSSQL_INSTANCE=DMSQL

MSSQL_DRIVER_VERSION=12.10.0

MSSQL_VERSION=16

LIQUIBASE_VERSION=5.0.3

MSSQL_MEDIA_URL=https://mssqlisostrorage.blob.core.windows.net/software/SQLServer2022-x64-ENU.iso?sp=r&st=2026-06-30T11:38:51Z&se=2030-06-30T19:53:51Z&spr=https&sv=2026-02-06&sr=c&sig=iXbvWp0WO4jAvG6ge4Zi5waFNhm%2FIGGZsDrsEQUzen4%3D

MSSQL_MEDIA_SHA256=342FC9F4B89EAA50A0D1EF0D30470EA7B6AF91B425C26023461198CB4E925B4F

MSSQL_SVC_ACCOUNT=NT AUTHORITY\SYSTEM