MSSQL_HOST=localhost
MSSQL_PORT=1433

MSSQL_DB=EcommerceMSSQL

MSSQL_USER=sa
MSSQL_PASSWORD=TerraformSA@2022!

MSSQL_INSTANCE=MSSQLSERVER

MSSQL_VERSION=2022
MSSQL_DRIVER_VERSION=12.10.0

LIQUIBASE_VERSION=5.0.3
