MSSQL_HOST=localhost
MSSQL_PORT=1533

MSSQL_DB=EcommerceMSSQL

MSSQL_USER=sa
MSSQL_PASSWORD=TerraformSA@2022!

MSSQL_INSTANCE=DMSQL

MSSQL_DRIVER_VERSION=12.10.0

MSSQL_VERSION=2025

LIQUIBASE_VERSION=5.0.3
MSSQL_INSTANCE=DMSQL